<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        $barangs = [
            [
                'stock_code' => '3891',
                'part_number' => 'JAM72S30-540/MR',
                'mnemonic' => 'JASOLAR',
                'nama_barang' => 'SOLAR PANEL MODULE MONO',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'PCS',
                'qty' => 480,
                'soh_odoo' => 480,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3891',
                'status' => 'approved',
                'stok' => 480,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3879',
                'part_number' => 'LR5-72HPH-540M',
                'mnemonic' => 'LONGI',
                'nama_barang' => 'SOLAR PANEL MODULE MONO',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'PCS',
                'qty' => 156,
                'soh_odoo' => 156,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3879',
                'status' => 'approved',
                'stok' => 156,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3879',
                'part_number' => 'LR5-72HPH-545M',
                'mnemonic' => 'LONGI',
                'nama_barang' => 'SOLAR PANEL MODULE MONO',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'PCS',
                'qty' => 77,
                'soh_odoo' => 77,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3879B',
                'status' => 'approved',
                'stok' => 77,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '4183',
                'part_number' => 'JKM590N-72HL-V',
                'mnemonic' => 'JINKO',
                'nama_barang' => 'MODULE MONOFACIAL N-TYPE TOPCON',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'PCS',
                'qty' => 615,
                'soh_odoo' => 615,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC4183',
                'status' => 'approved',
                'stok' => 615,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '4360',
                'part_number' => 'JKM580N-72HL-V',
                'mnemonic' => 'JINKO',
                'nama_barang' => 'MODULE MONOFACIAL N-TYPE TOPCON',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'PCS',
                'qty' => 53,
                'soh_odoo' => 53,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC4360',
                'status' => 'approved',
                'stok' => 53,
                'location' => 'CLE/UNG5',
                'remarks' => 'PAM TCAM 4 PCS',
            ],
            [
                'stock_code' => '4439',
                'part_number' => 'JKM570N-72HL-BDV',
                'mnemonic' => 'JINKO',
                'nama_barang' => 'MODULE BIFACIAL N-TYPE TOPCON',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'PCS',
                'qty' => 1104,
                'soh_odoo' => 1104,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC4439',
                'status' => 'approved',
                'stok' => 1104,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '4398',
                'part_number' => 'TSM-DE21.M.08',
                'mnemonic' => 'TRINA',
                'nama_barang' => 'PV MODULE TSM-DE21 Mono PERC M-685W',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'PCS',
                'qty' => 53,
                'soh_odoo' => 53,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC4398',
                'status' => 'approved',
                'stok' => 53,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '4401',
                'part_number' => 'TSM-NE19R.625',
                'mnemonic' => 'TRINA',
                'nama_barang' => 'PV MODULE TSM-NE19R N-TYPE 625W BLACKSHEET',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'PCS',
                'qty' => 1116,
                'soh_odoo' => 1116,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC4401',
                'status' => 'approved',
                'stok' => 1116,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3892',
                'part_number' => '1003032',
                'mnemonic' => 'SMA',
                'nama_barang' => 'INVERTER SMA STP8.0-3AV-40 W DISPLAY',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 12,
                'soh_odoo' => 12,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3892',
                'status' => 'approved',
                'stok' => 12,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3883',
                'part_number' => '1003021',
                'mnemonic' => 'SMA',
                'nama_barang' => 'INVERTER SMA STP15000TL W DISPLAY',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 13,
                'soh_odoo' => 13,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3883',
                'status' => 'approved',
                'stok' => 13,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3882',
                'part_number' => '1003023',
                'mnemonic' => 'SMA',
                'nama_barang' => 'INVERTER SMA STP20000TL W DISPLAY',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 1,
                'soh_odoo' => 1,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3882',
                'status' => 'approved',
                'stok' => 1,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3881',
                'part_number' => '1003024',
                'mnemonic' => 'SMA',
                'nama_barang' => 'INVERTER SMA STP25000TL W DISPLAY',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 33,
                'soh_odoo' => 33,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3881',
                'status' => 'approved',
                'stok' => 33,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3880',
                'part_number' => '1003091',
                'mnemonic' => 'SMA',
                'nama_barang' => 'INVERTER SMA STP50-40 CORE 1',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 3,
                'soh_odoo' => 3,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3880',
                'status' => 'approved',
                'stok' => 3,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3890',
                'part_number' => '2003018',
                'mnemonic' => 'SMA',
                'nama_barang' => 'DATA MANAGER M EEMAL-10',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 9,
                'soh_odoo' => 9,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3890',
                'status' => 'approved',
                'stok' => 9,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3888',
                'part_number' => '2003017',
                'mnemonic' => 'SMA',
                'nama_barang' => 'ENERGY METER',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 10,
                'soh_odoo' => 10,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3888',
                'status' => 'approved',
                'stok' => 10,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3889',
                'part_number' => '2003048',
                'mnemonic' => 'SMA',
                'nama_barang' => 'POWER SUPPLY CLCON',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 16,
                'soh_odoo' => 16,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3889',
                'status' => 'approved',
                'stok' => 16,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3887',
                'part_number' => '2003014',
                'mnemonic' => 'SMA',
                'nama_barang' => 'SURGE ARRESTOR DCSPD/KIT3',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 67,
                'soh_odoo' => 67,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3887',
                'status' => 'approved',
                'stok' => 67,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3885',
                'part_number' => '2003045',
                'mnemonic' => 'SMA',
                'nama_barang' => 'SURGE ARRESTOR ACSPD-KIT1',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 4,
                'soh_odoo' => 4,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3885',
                'status' => 'approved',
                'stok' => 4,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '3884',
                'part_number' => '2003015',
                'mnemonic' => 'SMA',
                'nama_barang' => 'SURGE ARRESTOR DCSPD/KIT4',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 4,
                'soh_odoo' => 4,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC3884',
                'status' => 'approved',
                'stok' => 4,
                'location' => 'CLE/UNG5',
            ],
            [
                'stock_code' => '5924',
                'part_number' => 'SUN2000-20KTL-M2',
                'mnemonic' => 'HUAWEI',
                'nama_barang' => 'INVERTER 20KTL',
                'warehouse' => 'CLE/UNG5',
                'uom' => 'UNIT',
                'qty' => 3,
                'soh_odoo' => 3,
                'outstanding_belum_wr' => 0,
                'difference' => 0,
                'kode_barcode' => 'BC5924',
                'status' => 'approved',
                'stok' => 3,
                'location' => 'CLE/UNG5',
                'remarks' => 'kisar Art Indonesia',
            ],
        ];

        foreach ($barangs as $barang) {
            DB::table('barang')->insert([
                'stock_code' => $barang['stock_code'],
                'part_number' => $barang['part_number'],
                'mnemonic' => $barang['mnemonic'],
                'nama_barang' => $barang['nama_barang'],
                'warehouse' => $barang['warehouse'],
                'uom' => $barang['uom'],
                'qty' => $barang['qty'],
                'soh_odoo' => $barang['soh_odoo'],
                'outstanding_belum_wr' => $barang['outstanding_belum_wr'],
                'difference' => $barang['difference'],
                'kode_barcode' => $barang['kode_barcode'],
                'status' => $barang['status'],
                'stok' => $barang['stok'],
                'location' => $barang['location'],
                'remarks' => $barang['remarks'] ?? null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
